### ISSUE TITLE
CI scratch image generation are failing due to storage issues

### ISSUE THREAD

**Issue by sarroutbi** [fedora-ci/dist-git-build-pipeline#34]
CI scratch image generation is failing:
https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-build-pipeline/job/master/32347/console

`...
OSError: [Errno 28] No space left on device
...`

A mechanism to avoid scratch image generation failures due to storage issues should be implemented

**Comment by thrix** [comment]
@msrb ptal pls
