### ISSUE TITLE
Failed builds when branch name is not a Fedora release name

### ISSUE THREAD

**Issue by clebergnu** [fedora-ci/dist-git-build-pipeline#9]
WRT PR https://src.fedoraproject.org/rpms/python-avocado/pull-request/16 , I noticed the "Fedora CI - scratch build" fails because branch name is not a Fedora release name.

Relevant console output:

```
+ cd python-avocado
+ fedpkg --release 82lts srpm
Could not execute srpm: Could not find the release/dist from branch name 82lts
Please specify with --release
```

Shouldn't the job pick a default (latest Fedora?) when the branch name doesn't match a release?

**Comment by msrb** [comment]
Thanks for the bug report @clebergnu and thanks for the [pull request](https://github.com/fedora-ci/dist-git-build-pipeline/pull/10) @thrix :)

This should be fixed now.
